language: node_js
node_js:
- "12.18.1"

services:
- "mongodb"

install:
- npm install newman
- npm install

before_script:
- node --version
- npm --version
- node_modules/.bin/newman --version

script:
- node_modules/.bin/newman run tests/Logs.postman_collection.json
